version: "3.8"
services:
  app:
    container_name: client-container
    image: anhtu269/client-docker
    build:
      context: ./client
      target: production
    ports:
      - "5002:80"
    networks:
      - api-dashboard-network
  server:
    container_name: server-container
    image: anhtu269/server-docker
    build:
      context: ./server/video-editing-api
      target: production
      dockerfile: server/video-editing-api/video-editing-api/Dockerfile
    ports:
      - "44394:44394"
    environment:
      - ConnectionString=mongodb+srv://anhtu123:anhtu123456@cluster0.ig9fqnx.mongodb.net/?retryWrites=true&w=majority
    networks:
      - api-dashboard-network
networks:
  api-dashboard-network:
    name: api-dashboard-network
    driver: bridge

